addSbtPlugin("com.jsuereth"       % "sbt-pgp"                       % "2.0.0")
addSbtPlugin("com.github.gseitz"  % "sbt-release"                   % "1.0.11")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"                  % "3.8")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "0.6.29")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "0.6.1")
addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "0.6.1")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.3.9")
